### ISSUE TITLE
Checklist todo before V1

### ISSUE THREAD

**Issue by mallardduck** [mallardduck/laravel-HumanoID#2]
The TODO List:

- [ ] Write better config/init docs (make it clear how to not foot-gun)
- [ ] Ponder future API for upstream Hasher/Salt concept
- [ ] Implement Eloquent integrations (model trait, interface, etc) [maybe V2]

### Better Docs
These should cover the basics of usage - which is pretty simple so readme does most that. We should also reiterate the concerns expressed in the upstream repo about not causing yourself future issues. Potentially since this is a Laravel integration package we should both: scream these concerns loudly and document intentional choices I made here to reduce sharp edges. (i.e. provide explanations and best practices)

### Ponder future API for upstream hasher/salt
Basically what it says - the upstream API shouldn't change _ALL that much_ however any changes it does have shouldn't completely blow up our progress. Right now that's not the case, however integrating to Eloquent for the DB magic would be something it could affect.

Specifically because I'm imagining a potential scenario where someone has a desire for differing HumanoID instances per Model. This could allow for easy use where you want different model types to have distinctly different themed HumanoID slugs.

### Finally, integrate better with Eloquent
This mostly speaks for itself - however it will be lowest priority task as it's the most at risk of change. Once other areas are stabilized this should be easy to pull off. As mentioned any integration to Eloquent before the upstream feature is added would be premature.

Things to consider are:
- Route Bindings per Model,
- Custom Generator per Model,
- Custom string style/formatting per Model,
- Deciding on: Save to Model, or Generate/Parse on fly, or BOTH via Config options?
- Determine the best way to bind models w/ decided constraints

The ability to either default to global, or set custom hasher/generator, per Model is very compelling. As such this should be the primary target for these integrations rather than any more simple approaches. Any basic integration could be done in user-land app code just as easily with low maintenance. So for now excluding this code is a feature!

**Comment by mallardduck** [comment]
Just for now pull from `dev-main` as I'd rather not bother with tagging a release yet. Soon though ™️

**Comment by emmadesilva** [comment]
I think the generator per-model is a very compelling feature. Just having an easy way to swap wordsets for different models would be cool. That way you can see at a glance if a model is for a user, a product, etc.

When benchmarking we mainly tested CPU time, I'm curios as to the memory usage. Is it negligible or could performance be affected that way if we have multiple generator instances for different wordsets in memory? Is there a good way to measure memory usage?

**Comment by emmadesilva** [comment]
@mallardduck lemme know if there is anything I can help with :)
